### ISSUE TITLE
Trying to install @egjs/ngx-view360@next, but got errors.

### ISSUE THREAD

**Issue by JoseRobertoReyesEncora** [naver/egjs-view360#405] opened 2023-02-24 18:40 UTC
## Description
I tried to install the Angular 4.0 beta version of the package, but got the next error when executing `npm install`:
```
npm ERR! code 254
npm ERR! path ~/project/node_modules/@egjs/view360
npm ERR! command failed
npm ERR! command sh -c npm i --prefix test/unit
npm ERR! npm ERR! code ENOENT
npm ERR! npm ERR! syscall open
npm ERR! npm ERR! path ~/project/node_modules/@egjs/view360/test/unit/package.json
npm ERR! npm ERR! errno -2
npm ERR! npm ERR! enoent ENOENT: no such file or directory, open '~/project/node_modules/@egjs/view360/test/unit/package.json'
npm ERR! npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! npm ERR! enoent 
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     ~/.npm/_logs/2023-02-24T18_28_09_456Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2023-02-24T18_28_02_898Z-debug-0.log
```

## Steps to check or reproduce
Just trying to install the package `npm install @egjs/ngx-view360@next`.
ng version result:
```
Angular CLI: 15.1.6
Node: 19.0.0 (Unsupported)
Package Manager: npm 9.5.1
OS: darwin x64
```
log:
[2023-02-24T18_28_09_456Z-debug-0.log](https://github.com/naver/egjs-view360/files/10827861/2023-02-24T18_28_09_456Z-debug-0.log)

**Comment by WoodNeck** [comment] 2023-02-27 03:30
Hello @JoseRobertoReyesEncora! Thanks for reporting the issue.
The issue is fixed on beta.4, try reinstalling the package.
```sh
npm i --save @egjs/ngx-view360@next
```

If that doesn't reinstall the newest version(`beta.4`), try running this script
```sh
npm cache clean -f
```

**Closed** 2023-02-27 06:29 UTC
Labels: :bug: Bug, :bookmark:4.x
